version: '2'

services:
  wso2apim:
    image: wso2am
    ports:
      - 8443:9443

  wso2ei-integrator:
    image: wso2ei
    command: sh -c "wso2ei-6.4.0-integrator"
    ports:
      - 9443:9443

  wso2ei-broker:
    image: wso2ei
    command: sh -c "wso2ei-6.4.0-broker"
    ports:
      - 9446:9446

  wso2ei-business-process:
    image: wso2ei
    command: sh -c "wso2ei-6.4.0-business-process"
    ports:
      - 9445:9445

  wso2ei-analytics-dashboard:
    image: wso2ei
    command: sh -c "wso2ei-6.4.0-analytics-dashboard"
    ports:
      - 9643:9643

  wso2ei-msf4j:
    image: wso2ei
    command: sh -c "wso2ei-6.4.0-msf4j"

  wso2ei-analytics-worker:
    image: wso2ei
    command: sh -c "wso2ei-6.4.0-analytics-worker"
